### ISSUE TITLE
Package Manager Error

### ISSUE THREAD

**Issue by pjotrpottervogel** [OCB7D2D/UnityTextureChannelPacker#1]
Hi I get following error messeages:

[Package Manager Window] Unable to add package [https://github.com/OCB7D2D/UnityTextureChannelPacker.git#upm@master]:
  Manifest [E:\UnityProjekte\a21_Trees\Library\PackageCache\ch.ocbnet.texturechannelpacker@9e9ee669dc\package.json] is invalid:
    Version 'master' is invalid. Expected a 'SemVer' compatible value.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/OCB7D2D/UnityTextureChannelPacker.git#upm@master]:
  Manifest [E:\UnityProjekte\a21_Trees\Library\PackageCache\ch.ocbnet.texturechannelpacker@9e9ee669dc\package.json] is invalid:
    Version 'master' is invalid. Expected a 'SemVer' compatible value. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Error adding package: https://github.com/OCB7D2D/UnityTextureChannelPacker.git#upm@master.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by mgreter** [comment]
Seems newer Unity versions are more strict, should be fixed now (it will say version 9999.0.0 for master/live branch). Thx!

**Comment by pjotrpottervogel** [comment]
Thank you, man - you do incredible mods!


Marcel Greter ***@***.***> schrieb am Fr., 14. Juli 2023,
14:24:
