### ISSUE TITLE
Question about Texture Channel Packer

### ISSUE THREAD

**Issue by donjon56** [OCB7D2D/UnityTextureChannelPacker#2]
Question about settings in this image as shown in your Readme:

![image](https://github.com/OCB7D2D/UnityTextureChannelPacker/assets/32038380/b65799e4-fde0-4723-a63b-6e31a6f54655)

In this screenshot all lava maps have `G` channel selected?

What does `G` checkbox do when selected here?

**Comment by mgreter** [comment]
It's the channel of the input texture that will be sampled.
With a monochrome texture it doesn't really matter which one you use.
- input green of "laval_ao" will go into resulting green channel
- input green of "laval_e" will go into resulting blue channel
- input green of "lava_r" will go into resulting alpha channel

**Comment by donjon56** [comment]
So for Emissive.... if the data had different values in RGB you might want to select all three to combine into the blue channel?

**Comment by mgreter** [comment]
Then the option in the drop-down becomes important; AFAIR there is "Max", "Min" and "Avg" ...
Edit: This may or may not work for your emission texture, maybe better to create something in "photoshop".
